apiVersion: v1
kind: Pod
metadata:
  name: pyspark-runner
spec:
  containers:
    - name: pyspark
      image: python:3.12-slim
      command:
        - /bin/bash
        - -c
        - |
          pip install pyspark &&
          curl -O https://raw.githubusercontent.com/example-user/spark-scripts/main/pyspark_demo.py &&
          python pyspark_demo.py
          sleep infinity

