apiVersion: v1
kind: Pod
metadata:
  name: pyspark-runner
spec:
  containers:
    - name: pyspark
      image: python:3.12-slim
      command:
        - /bin/bash
        - -c
        - |
          apt-get update && \
          apt-get install -y curl && \
          pip install --upgrade pip && \
          pip install pyspark && \
          curl -O https://raw.githubusercontent.com/Adityakumarjha1997/Test_azure/main/python.py && \
          python python.py && \
          sleep infinity
